name: ci

on: [push]

jobs:
  tests:
    name: Forge Testing
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        profile: [via-ir,min-solc,min-solc-via-ir,intense,solc-past-versions-0,solc-past-versions-1]

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Run Lint Check
        run: forge fmt --check

      - name: Run Tests with ${{ matrix.profile }}
        run: >
          ( [ "${{ matrix.profile }}" = "solc-past-versions-0" ] && 
            forge test --use 0.8.5 && 
            forge test --use 0.8.6 && 
            forge test --use 0.8.7 && 
            forge test --use 0.8.8 && 
            forge test --use 0.8.9 && 
            forge test --use 0.8.10 &&
            forge test --use 0.8.11  
          ) || 
          ( [ "${{ matrix.profile }}" = "solc-past-versions-1" ] && 
            forge test --use 0.8.12 && 
            forge test --use 0.8.13 && 
            forge test --use 0.8.14 && 
            forge test --use 0.8.15 && 
            forge test --use 0.8.16 && 
            forge test --use 0.8.17 
          ) || 
          FOUNDRY_PROFILE=${{ matrix.profile }} forge test
