name: ci

on:
  push:
    paths:
      - '**.sol'
      - '**.yml'

jobs:
  tests:
    name: Forge Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile: [via-ir,min-solc,min-solc-via-ir,intense,solc-past-versions-0,solc-past-versions-1,post-shanghai,post-shanghai-via-ir]

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Run Lint Check
        run: forge fmt --check

      - name: Run Tests with ${{ matrix.profile }}
        run: >
          ( [ "${{ matrix.profile }}" = "post-shanghai" ] && 
            forge test --use 0.8.22 --evm-version "shanghai"
          ) ||
          ( [ "${{ matrix.profile }}" = "post-shanghai-via-ir" ] && 
            forge test --use 0.8.22 --evm-version "shanghai" --via-ir
          ) ||
          ( [ "${{ matrix.profile }}" = "solc-past-versions-0" ] &&
            forge test --use 0.8.5 &&
            forge test --use 0.8.6 &&
            forge test --use 0.8.7 &&
            forge test --use 0.8.8 &&
            forge test --use 0.8.9 &&
            forge test --use 0.8.10 &&
            forge test --use 0.8.11 &&
            forge test --use 0.8.12
          ) ||
          ( [ "${{ matrix.profile }}" = "solc-past-versions-1" ] &&
            forge test --use 0.8.13 &&
            forge test --use 0.8.14 &&
            forge test --use 0.8.15 &&
            forge test --use 0.8.16 &&
            forge test --use 0.8.17 &&
            forge test --use 0.8.18 &&
            forge test --use 0.8.19 &&
            forge test --use 0.8.20 &&
            forge test --use 0.8.21
          ) ||
          FOUNDRY_PROFILE=${{ matrix.profile }} forge test

  codespell:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_filenames: true
          ignore_words_list: usera
          skip: ./.git,package-lock.json,ackee-blockchain-solady-report.pdf,EIP712Mock.sol
